### ISSUE TITLE
autolite CLI does not work from any dir

### ISSUE THREAD

**Issue by avitalyahel** [avitalyahel/autolite#31]
when user is not in the folder autolite doesn't reach the settings file

**Comment by avitalyahel** [comment]
```
09:23:56 avital@Avitals-Mac.local:()[hub]$ autolite system list
Traceback (most recent call last):
  File "/usr/local/bin/autolite", line 95, in <module>
    sys.exit(autolite(arguments))
  File "/usr/local/bin/autolite", line 63, in autolite
    db.init()
  File "/Users/avital/git/hub/autolite/db.py", line 59, in init
    connect()
  File "/Users/avital/git/hub/autolite/db.py", line 44, in connect
    g_db_path = os.path.expanduser(settings.read().db_path)
  File "/Users/avital/git/hub/autolite/settings.py", line 11, in read
    with open(SETTINGS_DEFAULT) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'settings-default.yaml'
```

**Comment by avitalyahel** [comment]
Done.
